# =========================
# Path setup (MUST be first)
# =========================
import sys
import os
from pathlib import Path

ROOT_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
if ROOT_DIR not in sys.path:
    sys.path.insert(0, ROOT_DIR)

BASE_DIR = Path(__file__).resolve().parent
LOGO_PATH = BASE_DIR / "ui" / "assets" / "company_logo.png"

from services.user_insights import (
    get_user_or_case_insights,
    get_pending_cases,
    get_overdue_cases,
    get_critical_cases
)

# =========================
# Imports
# =========================
import streamlit as st
import pickle
import faiss
from sentence_transformers import SentenceTransformer
from services.retriever import find_similar_cases
import pandas as pd

# =========================
# Load CSS
# =========================
def load_css():
    with open("app/ui/style.css") as f:
        st.markdown(f"<style>{f.read()}</style>", unsafe_allow_html=True)

    # hide Control Panel heading text ONLY (logic stays)
    st.markdown("""
        <style>
            .control-panel-hidden h3 {
                display: none;
            }
        </style>
    """, unsafe_allow_html=True)

# =========================
# Streamlit UI Config
# =========================
st.set_page_config(
    page_title="Auto MPR Recommendation",
    layout="wide"
)

load_css()

# =========================
# Sidebar Branding (polished)
# =========================
with st.sidebar:
    st.image(str(LOGO_PATH), use_container_width=True)
    st.markdown("<h3 style='margin-top:10px;'>Auto MPR</h3>", unsafe_allow_html=True)
    st.caption("Internal AI Demo")

# =========================
# Center Logo (theme-safe)
# =========================
st.markdown("<div style='display:flex; justify-content:center; margin-top:16px;'>", unsafe_allow_html=True)
st.image(str(LOGO_PATH), width=160)
st.markdown("</div>", unsafe_allow_html=True)

# =========================
# Brand Strip (no text)
# =========================
st.markdown(
    """
    <div style="
        height:52px;
        margin:18px auto 30px auto;
        border-radius:14px;
        max-width:1100px;
        background: linear-gradient(90deg, #7b2ff7, #f107a3);
    ">
    </div>
    """,
    unsafe_allow_html=True
)

# =========================
# Title
# =========================
st.markdown(
    "<h1 style='text-align:center;'>Auto MPR Response Recommendation</h1>",
    unsafe_allow_html=True
)

st.caption(
    "Recommendations are generated by semantically matching new MPR issues "
    "with historical cases using NLP-based similarity search."
)

# =========================
# Query Mode Selector (CENTERED)
# =========================
st.markdown("<br>", unsafe_allow_html=True)

c1, c2, c3 = st.columns([1, 2, 1])
with c2:
    query_mode = st.radio(
        "",
        ["General MPR Issue", "User-Specific View"],
        horizontal=True
    )


# =========================
# Load heavy resources
# =========================
scale = "2k"

@st.cache_resource
def load_resources(scale):
    model = SentenceTransformer("all-MiniLM-L6-v2")
    index = faiss.read_index(f"data/case_index_{scale}.faiss")
    with open(f"data/case_meta_{scale}.pkl", "rb") as f:
        metadata = pickle.load(f)
    return model, index, metadata

model, index, metadata = load_resources(scale)

# =========================
# User Input Section (centered)
# =========================
st.markdown('<div class="section-card">', unsafe_allow_html=True)

c1, c2, c3 = st.columns([1, 2, 1])
with c2:
    if query_mode == "General MPR Issue":
        query = st.text_area(
            "Enter MPR Issue",
            height=100,
            placeholder="Describe the issue..."
        )
    else:
        user_id = st.text_input(
            "Enter CaseID or User Name",
            placeholder="e.g. Kumar Sanu"
        )

    run_clicked = st.button("Run", use_container_width=True)

st.markdown('</div>', unsafe_allow_html=True)

# =========================
# Session State Init
# =========================
if "user_summary" not in st.session_state:
    st.session_state.user_summary = None

if "active_owner" not in st.session_state:
    st.session_state.active_owner = None

# =========================
# UX FIX: Reset stale state when switching modes
# =========================
if query_mode == "General MPR Issue":
    st.session_state.user_summary = None
    st.session_state.active_owner = None

# =========================
# General MPR Flow
# =========================
if run_clicked and query_mode == "General MPR Issue":
    if not query.strip():
        st.warning("Please enter an MPR issue.")
    else:
        with st.spinner("Searching similar past MPRs..."):
            results = find_similar_cases(
                query=query,
                model=model,
                index=index,
                metadata=metadata
            )

        results = sorted(results, key=lambda x: x.get("confidence", 0), reverse=True)

        st.markdown('<div class="section-card">', unsafe_allow_html=True)
        st.subheader("🔍 Similar Historical Cases")

        IMPORTANT_FIELDS = [
            "caseid", "category", "statuscode", "currentowner",
            "reportedon", "aging", "subject", "details", "Resolution"
        ]

        for i, r in enumerate(results, 1):
            confidence = round(r.get("confidence", 0), 2)
            label = "🟢 Best Match" if i == 1 else ""

            with st.expander(f"Case {i} {label} — Match Confidence: {confidence}%"):
                for field in IMPORTANT_FIELDS:
                    if field in r and r[field]:
                        st.write(f"**{field}**: {r[field]}")

        st.markdown('</div>', unsafe_allow_html=True)

        # =========================
        # 🧠 AI Recommended Resolution (DEMO)
        # =========================
        st.markdown('<div class="section-card">', unsafe_allow_html=True)
        st.subheader("🧠 Recommended Resolution")
        st.markdown("""
        **Suggested Action:**
        • Verify customer account details and recent activity  
        • Reprocess the transaction after clearing validation errors  
        • If issue persists, escalate to L2 Ops with case context  

        _This recommendation is generated by analyzing similar historical MPR cases._
        """)
        st.markdown('</div>', unsafe_allow_html=True)

# =========================
# User / Case Insights
# =========================
if run_clicked and query_mode == "User-Specific View":
    if not user_id.strip():
        st.warning("Please enter a caseID or full name.")
    else:
        insights = get_user_or_case_insights(user_id)

        if insights["data"] is None:
            st.error("No data found for the given input.")
        else:
            if insights["type"] == "case":
                case = insights["data"]
                st.markdown('<div class="section-card">', unsafe_allow_html=True)
                st.subheader(f"📄 Case Details — {case['caseid']}")
                st.json(case)
                st.markdown('</div>', unsafe_allow_html=True)
                
                st.session_state.user_summary = None
                st.session_state.active_owner = None
            else:
                st.session_state.user_summary = insights["data"]
                st.session_state.active_owner = insights["data"]["owner"]

# =========================
# User Summary View
# =========================
if st.session_state.user_summary is not None:
    summary = st.session_state.user_summary
    owner = st.session_state.active_owner

    st.markdown('<div class="section-card">', unsafe_allow_html=True)
    st.subheader(f"👤 User Summary — {owner}")

    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Total Cases", summary["total_cases"])
    c2.metric("Pending", summary["pending_cases"])
    c3.metric("Overdue (>7d)", summary["overdue_cases"])
    c4.metric("Critical (>21d)", summary["critical_cases"])

    st.markdown("### Status Breakdown")
    st.json(summary["status_breakdown"])

    # =========================
    # 📊 User Analytics (Charts)
    # =========================
    chart_col1, chart_col2 = st.columns(2)

    with chart_col1:
        st.markdown("#### Case Status Distribution")
        status_df = pd.DataFrame(
            list(summary["status_breakdown"].items()),
            columns=["Status", "Count"]
        )
        # Fix: Direct use of matplotlib figure via pyplot
        import matplotlib.pyplot as plt
        fig1, ax1 = plt.subplots()
        status_df.set_index("Status").plot.pie(y="Count", autopct="%1.0f%%", legend=False, ax=ax1)
        st.pyplot(fig1)

    with chart_col2:
        st.markdown("#### Case Aging Severity")
        aging_df = pd.DataFrame({
            "Category": ["Pending", "Overdue", "Critical"],
            "Cases": [
                summary["pending_cases"],
                summary["overdue_cases"],
                summary["critical_cases"]
            ]
        })
        st.bar_chart(aging_df.set_index("Category"))

    st.markdown('</div>', unsafe_allow_html=True)

    # =========================
    # Focused Case View
    # =========================
    st.markdown('<div class="section-card">', unsafe_allow_html=True)
    st.subheader("📌 Focused Case View")

    case_type = st.radio(
        "Select case category",
        ["Pending", "Overdue", "Critical"],
        horizontal=True
    )

    if case_type == "Pending":
        cases = get_pending_cases(owner)
        badge = "🟡 Pending"
        empty_msg = "No pending cases found for this user."
    elif case_type == "Overdue":
        cases = get_overdue_cases(owner)
        badge = "🟠 Overdue"
        empty_msg = "No overdue cases found for this user."
    else:
        cases = get_critical_cases(owner)
        badge = "🔴 Critical"
        empty_msg = "No critical cases found for this user."

    if not cases:
        st.info(empty_msg)
    else:
        for c in cases:
            with st.expander(f"{badge} | Case {c['caseid']} | Aging: {c['aging']} days"):
                st.write(f"**Category:** {c['category']}")
                st.write(f"**Status:** {c['statuscode']}")
                st.write(f"**Reported On:** {c['reportedon']}")
                st.write(f"**Subject:** {c.get('subject','')}")
                st.write(f"**Details:** {c.get('details','')}")

    st.markdown('</div>', unsafe_allow_html=True)